name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream repository
      run: git remote add upstream https://github.com/LaolunsiG/PCR.git

    - name: Fetch and merge upstream
      run: |
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
